// server-middleware/secure-data.js
export default (req, res, next) => {
    const CHARTMAT_BOARD_BASE_URL = process.env.CHARTMAT_BOARD_BASE_URL;
    const CHARTMAT_STRIPE_PRIVATE_KEY = process.env.CHARTMAT_STRIPE_PRIVATE_KEY;
    const BEANSTALK_ENDPOINT = process.env.BEANSTALK_ENDPOINT;
    const CHARTMAT_GOOGLE_PICKER_API_KEY = process.env.CHARTMAT_GOOGLE_PICKER_API_KEY;
    const CHARTMAT_GOOGLE_APP_ID = process.env.CHARTMAT_GOOGLE_APP_ID;
    const CHARTMAT_MAPBOX_AUTH_TOKEN = process.env.CHARTMAT_MAPBOX_AUTH_TOKEN;
    const CHARTMAT_TEMPLATE_WORKSPACE_ID = process.env.CHARTMAT_TEMPLATE_WORKSPACE_ID;
    const CHARTMAT_PLATFORM_FEE_PERCENTS = process.env.CHARTMAT_PLATFORM_FEE_PERCENTS;

    res.end(JSON.stringify({ CHARTMAT_BOARD_BASE_URL, CHARTMAT_STRIPE_PRIVATE_KEY, BEANSTALK_ENDPOINT, CHARTMAT_GOOGLE_PICKER_API_KEY, CHARTMAT_GOOGLE_APP_ID, CHARTMAT_MAPBOX_AUTH_TOKEN, CHARTMAT_TEMPLATE_WORKSPACE_ID, CHARTMAT_PLATFORM_FEE_PERCENTS }));
  }
  